GaussianBlurDegradation:
  kernel_size:
    min: 1
    max: 4
    step: 2

MotionBlurDegradation:
  kernel_size:
    min: 1
    max: 4
    step: 1

GaussianNoiseDegradation:
  mean: 0
  std:
    min: 0.5
    max: 1
    step: 0.1

SaltPepperNoiseDegradation:
  prob:
    min: 0.001
    max: 0.01
    step: 0.001

BrightnessContrastDegradation:
  alpha:
    min: 0.8
    max: 1.2
    step: 0.1
  beta:
    min: -20
    max: 20
    step: 5

WaveDistortionDegradation:
  amplitude:
    min: 1
    max: 5
    step: 1
  frequency:
    min: 0.001
    max: 0.009
    step: 0.001

ShadowDegradation:
  direction: 
    - "diagonal"
    - "left"
    - "right"
    - "top"
    - "bottom"
  "intensity": 
    min: 0.1
    max: 0.6
    step: 0.1
  "blur":
    min: 50
    max: 300
    step: 50
  "len_percentage":
    min: 0.1
    max: 0.9
    step: 0.1

ColorFilterDegradation:
  red:
    min: 0.9
    max: 1.1
    step: 0.01
  green:
    min: 0.9
    max: 1.1
    step: 0.01
  blue:
    min: 0.9
    max: 1.1
    step: 0.01